name: Publish

on:
  release:
    types: [ published ] # Only publish to crates.io when we formally publish a release
  # For more on how to formally release on Github, read https://help.github.com/en/articles/creating-releases
env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Install jq
        run: sudo apt-get --force-yes install jq
      - uses: actions/checkout@v2
      - name: Calculate the version
        env:
          RELEASE_VERSION_STRING: ${{ github.ref }}
        run: |
          if [ $RELEASE_VERSION_STRING != 'refs/tags/v'$(cargo read-manifest | jq -r '.version') ]
          then
          exit 1
          fi
          # the next steps will be only executed if there is a TAG beginning with v
          # and with the VERSION in Cargo.toml,
          # for example v0.0.6
          #
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
      - name: Build
        run: cargo +nightly build --verbose
      - name: Test (Run cargo-tarpaulin)
        uses: actions-rs/tarpaulin@v0.1
        with:
          args: "-v --fail-under 100"
      - name: Delete tarpaulin output
        run: rm -f cobertura.xml
      - name: Login to crates.io
        run: cargo login $CRATES_IO_TOKEN
        env:
          CRATES_IO_TOKEN: ${{ secrets.crates_io_token }}
      - name: Publish
        run: cargo publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.crates_io_token }}
