name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install latest nightly
      uses: actions-rs/toolchain@v2
      with:
            profile: minimal
            toolchain: nightly
            override: true
            components: tarpaulin

    - uses: actions/checkout@v2
    - name: Build
      run: cargo +nightly build --verbose
    - name: Run tests
      run: cargo tarpaulin -v --fail-under 100
