name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
            profile: minimal
            toolchain: nightly
            override: true

    - uses: actions/checkout@v2
    - name: Build
      run: cargo +nightly build --verbose
    - name: Run cargo-tarpaulin
      uses: actions-rs/tarpaulin@v0.1
      with:
            version: '0.9.0'
            args: '-v --fail-under 100'
